gen-file=SerialGen
time-file=SerialTime

#---------GENERATIONS---------
gen: compile-gen run-gen
compile-gen:
	javac $(gen-file).java
run-gen:
	java $(gen-file)


#---------TIME---------
time: compile-time run-time
compile-time:
	javac $(time-file).java
run-time:
	java $(time-file)
